#!/bin/bash

NUMERO1=10
NUMERO2=5

SOMA=$(($NUMERO1 + $NUMERO2))
echo "$NUMERO1 + $NUMERO2 = $SOMA"

SUBTRACAO=$(($NUMERO1 - $NUMERO2))
echo "$NUMERO1 - $NUMERO2 = $SUBTRACAO"

MULTIPLICACAO=$(($NUMERO1 * $NUMERO2))
echo "$NUMERO1 * $NUMERO2 = $MULTIPLICACAO"

DIVISAO=$(($NUMERO1 / $NUMERO2))
echo "$NUMERO1 / $NUMERO2 = $DIVISAO"
